extends: .github
shared:
  DefaultQueueOptions: &DefaultQueueOptions
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}
    allow_inplace_checks: true
    merge_method: squash
  CheckRuns: &CheckRuns
    - check-success=linters
    - check-success=test-junit
    - check-success=test-scopes


scopes:
  source:
    files:
      # Used by .github/workflow/ci.yml to test the action
      everything: {}

merge_queue:
  max_parallel_checks: 5

priority_rules:
  - name: hotfix
    conditions:
      - label=hotfix
    priority: 2500

queue_rules:
  - name: hotfix
    <<: *DefaultQueueOptions
    autoqueue: true
    queue_conditions:
      - base = main
      - label = hotfix
    merge_conditions:
      - and: *CheckRuns
    branch_protection_injection_mode: merge

  - name: automated updates
    <<: *DefaultQueueOptions
    autoqueue: true
    queue_conditions:
      - base = main
      - or:
          - author = mergify-ci-bot
          - author = renovate[bot]
          - author = dependabot[bot]
    merge_method: merge
    merge_conditions:
      - and: *CheckRuns
    batch_size: 7
    batch_max_wait_time: 5min
    commit_message_template:
    queue_branch_merge_method: fast-forward


  - name: default
    <<: *DefaultQueueOptions
    autoqueue: true
    queue_conditions:
      - base = main
    merge_conditions:
      - and: *CheckRuns

pull_request_rules:
  - name: request review
    conditions:
      - -author=dependabot[bot]
      - -author=renovate[bot]
      - -author=mergify-ci-bot
      - -merged
      - -closed
      - check-success=all-greens
      - "#changes-requested-reviews-by=0"
      - review-requested!=@devs
      - and:
          - or:
              - label!=hotfix
              - not:
                  or: &HotfixReviewCond
                    # Author is engineering manager, we allow with one review
                    - and:
                        - author=@eng-mgr
                        - "#approved-reviews-by>=1"
                    - and:
                        - author = @devs
                        # in any other case, we allow if approve by engineering manager
                        # or anyone if it's a regular fix/revert
                        - or:
                            - approved-reviews-by = @eng-mgr
                            - and:
                                - title ~= ^(revert|fix)

          - not:
              or: &DefaultReviewCond
                - "#approved-reviews-by>=1"
                - author = dependabot[bot]
                - author = renovate[bot]
                - and:
                    - author = mergify-ci-bot
                    - head = openapi-spec-sync
                - and:
                    - author = mergify-ci-bot
                    - head ~= ^clifus/
                    - "title ~= ^chore: bump"
    actions:
      request_reviews:
        teams:
          - devs

merge_protections:
  - name: 🤖 Continuous Integration
    if:
      - label != hotfix
    success_conditions:
      - and: *CheckRuns

  - name: 👀 Review Requirements
    if:
      - label != hotfix
    success_conditions:
      - or: *DefaultReviewCond

merge_protections_settings:
  reporting_method: deployments
