name: gha-ci-issues
description: Upload JUnit XML report to Mergify CI Insights
author: Mergify
branding:
  icon: at-sign
  color: blue
inputs:
  token:
    required: true
    description: Mergify CI token
  report_path:
    required: true
    description: Path of the files to upload
  mergify_api_url:
    required: false
    description: URL of the Mergify API
    default: https://api.mergify.com
runs:
  using: composite
  steps:
    - name: Setup Python 🔧
      uses: actions/setup-python@v5.6.0
      with:
        python-version: "3.13"

    - name: Install dependencies
      shell: bash
      run: |
        pip install mergify-cli

    - shell: bash
      id: junit-upload
      env:
        MERGIFY_API_URL: ${{ inputs.mergify_api_url }}
        MERGIFY_TOKEN: ${{ inputs.token }}
        FILES: ${{ inputs.report_path }}
      run: |
        set -x -e
        mergify ci junit-upload ${FILES}
