name: gha-ci-issues
description: Upload JUnit XML report to Mergify CI Issues
author: Mergify
branding:
  icon: at-sign
  color: blue
inputs:
  token:
    required: true
    description: CI Issues Application Key
  report_paths:
    required: true
    description: Paths of the files to upload
  mergify_api_url:
    required: false
    description: URL of the Mergify API
    default: https://api.mergify.com
runs:
  using: composite
  steps:
    - name: Setup Python 🔧
      uses: actions/setup-python@v5.3.0
      with:
        python-version: 3.12.7

    - name: Install dependencies
      shell: bash
      run: |
        pip install mergify-cli

    - shell: bash
      id: gigid
      env:
        MERGIFY_API_URL: ${{ inputs.mergify_api_url }}
        MERGIFY_TOKEN: ${{ inputs.token }}
        FILES: ${{ inputs.report_paths }}
      run: |
        set -x -e
        mergify ci junit-upload "${FILES}"
