name: gha-ci-issues
description: Upload JUnit XML report to Mergify CI Insights
author: Mergify
branding:
  icon: at-sign
  color: blue
inputs:
  token:
    required: true
    description: Mergify CI token
  job_name:
    description: |
      Override the job name, must be used in case of matrix job to avoid
      having the same name for all jobs
  report_path:
    required: true
    description: Path of the files to upload
  mergify_api_url:
    required: false
    description: URL of the Mergify API
    default: https://api.mergify.com
  flaky_test_detection:
    required: false
    description: Mark test execution as part of a flaky test detection process
    default: "false"
runs:
  using: composite
  steps:
    - name: Setup Python 🔧
      uses: actions/setup-python@v6.0.0
      with:
        python-version: "3.13"

    - name: Install dependencies
      shell: bash
      run: |
        # pip install mergify-cli
        pip install git+https://github.com/Mergifyio/mergify-cli@devs/sileht/ci-fixes/Ib8db94a2562e627bf87592a78479856b4baacd40#egg=mergify-cli

    - shell: bash
      id: junit-process
      env:
        MERGIFY_API_URL: ${{ inputs.mergify_api_url }}
        MERGIFY_TEST_FLAKY_DETECTION: ${{ inputs.flaky_test_detection }}
        MERGIFY_TOKEN: ${{ inputs.token }}
        MERGIFY_JOB_NAME: ${{ inputs.job_name }}
        FILES: ${{ inputs.report_path }}
      run: |
        set -x -e
        mergify ci junit-process ${FILES}
