name: gha-mergify-ci
description: The Mergify CI integration with GitHub Actions
author: Mergify
branding:
  icon: at-sign
  color: blue
inputs:
  action:
    description: |
      The Mergify CI action:
      * junit-process: process JUnit XML files with Mergify CI Insights (Upload and Quarantine)
      * scopes: detect and upload pull requests scopes to Mergify Merge Queue
      * wait-jobs: wait for specified jobs to complete before proceeding
    # Backward compat
    default: junit-process
  token:
    description: Mergify CI token
  mergify_api_url:
    description: URL of the Mergify API
    default: https://api.mergify.com
  job_name:
    description: |
      Override the job name, must be used in case of matrix job to avoid
      having the same name for all jobs
  report_path:
    description: Path of the files to upload
  flaky_test_detection:
    description: Mark test execution as part of a flaky test detection process
    default: "false"
  jobs:
    description: List of jobs to wait for completion
outputs:
  scopes:
    description: stringified JSON mapping with names of all scopes matching any of changed files
    value: ${{ steps.scopes-detection.outputs.scopes }}
runs:
  using: composite
  steps:
    - name: Inputs checks
      shell: bash
      if: ${{ inputs.action != 'junit-process' && inputs.action != 'scopes' && inputs.action != 'wait-jobs' }}
      env:
        ACTION: ${{ inputs.action }}
      run: |
        echo "Unsupported action: $ACTION"
        echo "Valid actions are: junit-process, scopes, wait-jobs"
        exit 1

    - name: Setup Python 🔧
      uses: actions/setup-python@v6.0.0
      with:
        python-version: "3.14"

    - name: Install dependencies
      shell: bash
      run: |
        pip install mergify-cli

    - shell: bash
      id: junit-process
      if: inputs.action == 'junit-process'
      env:
        MERGIFY_API_URL: ${{ inputs.mergify_api_url }}
        MERGIFY_TEST_FLAKY_DETECTION: ${{ inputs.flaky_test_detection }}
        MERGIFY_TOKEN: ${{ inputs.token }}
        MERGIFY_JOB_NAME: ${{ inputs.job_name }}
        FILES: ${{ inputs.report_path }}
      run: |
        set -x -e
        mergify ci junit-process ${FILES}

    - name: Detect scopes
      if: inputs.action == 'scopes'
      id: scopes-detection
      shell: bash
      run: mergify ci scopes --write $RUNNER_TEMP/mergify-scopes.json

    - name: Upload scopes to Mergify API
      shell: bash
      if: inputs.token && inputs.action == 'scopes'
      env:
        MERGIFY_TOKEN: ${{ inputs.token }}
        MERGIFY_API_URL: ${{ inputs.mergify_api_url }}
      run: mergify ci scopes-send --file $RUNNER_TEMP/mergify-scopes.json

    - name: Wait jobs
      if: inputs.action == 'wait-jobs'
      uses: re-actors/alls-green@release/v1
      with:
        allowed-skips: ${{ inputs.jobs }}
        jobs: ${{ inputs.jobs }}
