services:
  mockServer:
    image: mockserver/mockserver:7.0.0@sha256:95a393d14e441684758dda2b8f473db7683f97ad74e0975620b95a34a85de49f
    command: -logLevel DEBUG
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/fake-ci-issue-api.json
    volumes:
      - type: bind
        source: zfixtures
        target: /config
  mockServerError:
    image: mockserver/mockserver:7.0.0@sha256:95a393d14e441684758dda2b8f473db7683f97ad74e0975620b95a34a85de49f
    command: -logLevel DEBUG
    ports:
      - 1085:1080
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/fake-ci-issue-api-500.json
    volumes:
      - type: bind
        source: zfixtures
        target: /config
