services:
  mockServer:
    image: mockserver/mockserver:7.4.0@sha256:fed9b2089e021947f785d1f0bfda3723352bb2c1634ce7b0bcd42dfd1b0fd02f
    command: -logLevel DEBUG
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/fake-ci-issue-api.json
    volumes:
      - type: bind
        source: zfixtures
        target: /config
  mockServerError:
    image: mockserver/mockserver:7.4.0@sha256:fed9b2089e021947f785d1f0bfda3723352bb2c1634ce7b0bcd42dfd1b0fd02f
    command: -logLevel DEBUG
    ports:
      - 1085:1080
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/fake-ci-issue-api-500.json
    volumes:
      - type: bind
        source: zfixtures
        target: /config
