name: Continuous Integration
permissions: read-all

on:
  pull_request:
    branches:
      - main
      - devs/**

concurrency:
  # yamllint disable-line rule:line-length
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linters:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Python 🔧
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.14.5

      - name: Check workflow files
        uses: docker://rhysd/actionlint:1.7.12@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667
        with:
          args: -color

      - name: Test 🔍
        run: |
          # nosemgrep: generic.ci.security.use-frozen-lockfile.use-frozen-lockfile-pip
          pip install semgrep yamllint
          semgrep --config=auto --error
          yamllint .

  autodoc:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: false

      - name: Regenerate documentation
        run: ./generate-doc.sh

      - name: Verify Changed files
        run: |
          if ! git diff --exit-code -- README.md; then
            echo "::error::Action documentation is out of date. Run \`./generate-doc.sh\`"
            exit 1
          fi


  test-scopes:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Trying action scopes-git-refs
        id: scopes-git-refs
        uses: ./
        with:
          action: scopes-git-refs
          mergify_config_path: zfixtures/mergify.yml

      - name: Trying action scopes-upload
        id: scopes-upload
        uses: ./
        with:
          action: scopes-upload
          token: ${{ secrets.MERGIFY_TOKEN }}
          scopes: scope1,scope2
          mergify_config_path: zfixtures/mergify.yml

      - name: Trying action scopes
        id: scopes-detection
        uses: ./
        with:
          action: scopes
          token: ${{ secrets.MERGIFY_TOKEN }}
          mergify_config_path: zfixtures/mergify.yml

      - name: Check scopes
        env:
          SCOPES: ${{ steps.scopes-detection.outputs.scopes }}
          EVERYTHING: ${{ fromJSON(steps.scopes-detection.outputs.scopes).everything }}
          EVERYTHING_BOOL: ${{ fromJSON(steps.scopes-detection.outputs.scopes).everything == 'true' }}
        run: |
          echo "SCOPES: $SCOPES"
          test "$EVERYTHING" == "true"
          test "$EVERYTHING_BOOL" == "true"

  test-junit:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Prepare mockserver
        run: |
          docker compose up -d
          sleep 1
          docker compose logs

      - name: Run action
        uses: ./
        with:
          action: junit-process
          token: fake-valid-token
          report_path: zfixtures/*.xml
          mergify_api_url: http://localhost:1080
          mergify_config_path: zfixtures/mergify.yml

      - name: Run action with error scenario ❌
        id: error500
        continue-on-error: true
        uses: ./
        with:
          action: junit-process
          token: fake-valid-token
          report_path: zfixtures/junit_example.xml
          mergify_api_url: http://localhost:1085
          mergify_config_path: zfixtures/mergify.yml

      - name: Dump mockserver logs
        if: always()
        run: |
          docker compose logs

  test-wait-jobs:
    needs: [test-junit, test-scopes, linters]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Trying action
        id: scopes-detection
        uses: ./
        with:
          action: wait-jobs
          jobs: ${{ toJSON(needs) }}
          mergify_config_path: zfixtures/mergify.yml

  all-greens:
    if: ${{ !cancelled() }}
    needs:
      - linters
      - autodoc
      - test-scopes
      - test-junit
      - test-wait-jobs
    runs-on: ubuntu-latest
    steps:
      - name: Verify all jobs succeeded
        uses: Mergifyio/gha-mergify-ci@b84ac7a157d960a0763fc24243af0bdafa2d3241 # v19
        with:
          action: wait-jobs
          jobs: ${{ toJSON(needs) }}
